### ISSUE TITLE
[Enhancement]support for android emulator

### ISSUE THREAD

**Issue by shiron-truong** [zebrunner/mcloud-agent#1]
Dear mcloud team,
I'd like to ask a support related to enhance mcloud, it would be great if mcloud can support to run the test on android emulator.
In the meantime, do we have any workaround solution to deal with it?

Many thanks and best regards,
Binh

**Comment by vdelendik** [comment]
already implemented using redroid emulator which can be integrated into the device farm.
Moreover, it might use regular ec2 instances for that: https://github.com/zebrunner/mcloud-redroid/releases/tag/1.0

**Comment by dhreben** [comment]
Closed
