### ISSUE TITLE
save docker logs before down

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#100]
let's save in one place all docker logs for devices before down/restart

**Comment by vdelendik** [comment]
done. to test setup using latest mcloud-agent; branch: develop
do down or restart for device(s)
-> log files should be saved in `/tmp/device-name-udid.log` and `-> log files should be saved in /tmp/device-name-udid-appium.log`

**Comment by dhreben** [comment]
Verifed.
