### ISSUE TITLE
revert #100 with logs generation as it slow down restarts etc

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#113]
let's revert https://github.com/zebrunner/mcloud-agent/issues/100 changes.
maybe we can think about something else like extra command line flags to keep logs...

for long running devices logs might be pretty huge and we spend seconds/minutes for restart which seems to be too much...

**Comment by vdelendik** [comment]
done, no more pause per each device container during down or restart

**Comment by dhreben** [comment]
Verified.
