### ISSUE TITLE
investigate possibility to use iOS devices without internet/wi-fi

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#114]
using adb and local connection for android devices we allow to emulate wi-fi enable/disable during the testing.
at the same time in iOS we rely on WDA which is too sensitive to the connection. As only wifi disable we can't send command to WDA...

investigate possibility to organize communication between server and device (WDA app) without ip and internat

**Comment by shamanec** [comment]
This is completely possible and really easy to achieve. To do it you can use `go-ios` to forward the WDA port from the device to the host: `go-ios forward 20104 20104` for example. It can be also achieved with any other tool that supports port forwarding from the device. It even seems to be just a little bit faster that way

https://user-images.githubusercontent.com/60219580/179025778-19804e13-857b-4950-ab78-5ddd6cf8adbb.mp4

**Comment by vdelendik** [comment]
related tickets:
https://github.com/zebrunner/appium/issues/148
https://github.com/zebrunner/mcloud-device/issues/118
https://github.com/zebrunner/mcloud-agent/issues/155

**Comment by vdelendik** [comment]
doe, to test we have attach iOS device via Linux and Mac and verify that device is accessible via STF when wi-fi connection is unavailable...

**Comment by dhreben** [comment]
Verified.
