### ISSUE TITLE
down command should ignore connected devices filter and remove forcibly containers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#117]
in case of any problem with udev and container removals on disconnect we might have corrupted/unhealthy containers up&running.
such invalid containers can't be removed as we verify that device is connected via /dev/device* symlink.

down by uuid or without it should remove forcibly all existing containers even if device is not connected

**Comment by vdelendik** [comment]
fixed. down by udid and without it will remove any existing device container(s)

**Comment by dhreben** [comment]
Verified.
