### ISSUE TITLE
automate upgrading steps to 2.2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#119]
in CE generation 2.x every repo should support upgrade steps on it's own. review the list of changes and automate steps if needed.

**Comment by vdelendik** [comment]
done. upgrade is pretty simple and include pulling latest changes and re-run ansible script

**Comment by dhreben** [comment]
Verified.

<img width="848" alt="Screenshot 2022-04-27 at 10 47 06" src="https://user-images.githubusercontent.com/50950954/165468230-d10d9016-e316-4ffe-af7d-e953c9d12f1e.png">
