### ISSUE TITLE
register extra crontab rule to restart farm on reboot

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#123]
let's try to register crontab expression on server reboot via ansible or setup script.
expression to add:
```
@reboot sleep 30 && zebrunner-farm restart
```

P.S. sleep 30 is TBD if needed

**Comment by dhreben** [comment]
docker logs -f device-Samsung_Galaxy_S5-4d.....aad21e7
```
Unknown arguments: connectDevDealer, connectAppDealer
Exit status: 1
```

**Comment by vdelendik** [comment]
closing as won't fix. tested successfully linux agent reboot with full CE and android/ios devices connected successfully.
if reboot happened when services were up&running then all of them starts automatically on system reboot.
