### ISSUE TITLE
reuse smart logic to download all developer images without hardcoded versions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#125]
we do have hardcoded number of iOS versions and corresponding developer images on public storage:
https://github.com/zebrunner/mcloud-agent/blob/97c77c8ec7d0f562a4c67dedc1daa5d4b98449d4/defaults/main.yml#L8

let's investigate possibility to get all exiting images from s3://zebrunner-ce/mcloud/DeveloperDiskImages/ and download/redownload if necessary.

As of now every new iOS major version requires fixes into this repo, i.e. extra pull and ansible script execution. goal: be able to download fresh versions without commits here

**Comment by vdelendik** [comment]
done. dev images should be auto downloaded on the start. make sure to test using several iOS devices with the same iOS version. As we going to reuse old common share it might be a conflict downloading the same dmg files in parallel.

**Comment by dhreben** [comment]
Verified.
