### ISSUE TITLE
investigate an option to dockerize usbmuxd connection

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#127]
detailed information about usbmuxd:
https://jon-gabilondo-angulo-7635.medium.com/understanding-usbmux-and-the-ios-lockdown-service-7f2a1dfd07ae

Ideally we wanna to provide to the device container access only to the single device. That's allow to minimize risks of the global failure when all iOS devices reconnected due to the single crash in usbmuxd service.

so after the quick look we have to start for each device their own instance of usbmuxd and share unique websocket file to communicate between container and device

**Comment by vdelendik** [comment]
according to the @shamanec such steps should make usbmuxd isolated per device:
```
so the concept is the following
First of all you need to have usbmuxd installed but not running on the host
without it being installed it seems that the devices don't connect over usb at all
after installing usbmuxd you need to mask the service using 'sudo systemctl mask usbmuxd' or completely remove this service
because if it starts automatically it will lock the devices to the host socket and they will not be available inside the container
then the container logic I have is
I have a udev rule that creates a symlink for each device in /dev
when I create a container I mount this symlink to it
and then inside the container I run withing my entrypoint script
'usbmuxd -f &' or whatever usbmuxd command you want
before doing other interactions with the device
after usbmuxd is ran you will get a Trust popup on the device (because the container is a new host)
and thats pretty much it
there are a few drawbacks this way
devices are never available to the host
```

**Comment by vdelendik** [comment]
done, setup mcloud-agent using develop branch and test according to the https://github.com/zebrunner/stf/issues/535 steps

**Comment by vdelendik** [comment]
interesting project to share usbmuxd outside: https://github.com/corellium/usbfluxd

**Comment by dhreben** [comment]
Verified.
