### ISSUE TITLE
bump up to 1.4.3 appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#132]
healthcheck improved for offline and unauthorized android devices: https://github.com/zebrunner/appium/releases/tag/1.4.3
we have to jump on this version asap

**Comment by vdelendik** [comment]
done. we can start upgrading all farms especially if android devices not stable and constantly go to disconnected state

**Comment by dhreben** [comment]
Closed as Appium 1.4.3. is quite stable
