### ISSUE TITLE
added support for iOS 15.5

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#134]
1. upgrade xcode to 13.4 
2. push 15.5 dev images dmg to public s3
3. add 15.5 into the defaults/main.yml

**Comment by vdelendik** [comment]
verified on mine own

**Comment by vdelendik** [comment]
reopening as WDA is crashed for 15.5

**Comment by vdelendik** [comment]
workaround: Prepare [WebDriverAgent.ipa](https://github.com/zebrunner/mcloud-agent#prepare-webdriveragentipa-file) using [v4.4.3](https://github.com/appium/WebDriverAgent/releases/tag/v4.4.3)

**Comment by dhreben** [comment]
**Verified.**

Test scenario:

1. ./zebrunner.sh down
2. .Git clone new WebdriverAgent https://github.com/appium/WebDriverAgent/releases/tag/v4.4.3 and add  to /Users/idmcloud/.nvm/versions/node/v14.15.1/lib/node_modules/appium/node_modules/appium-webdriveragent/ on Macmini 
2. `npm install`
3. Open WebDriverAgent.xcodeproj on Xcode
4. Build WebdriverAgent
5. Prepare [WebDriverAgent.ipa](https://github.com/zebrunner/mcloud-agent#prepare-webdriveragentipa-file) and add to Linux (only for iOS devices)
6. ./zebrunner.sh start (macmini)
7. Run tests on Simulator and iOS devices
   - Verify that video are available.
