### ISSUE TITLE
adjust setups steps removing customization of usbmuxd service

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#140]
neither udev rules nor usbmuxd.service should be adjusted on master host, i.e. these steps should be removed:
https://github.com/zebrunner/mcloud-agent#adjust-usbmuxd-service

Note: make sure describe reverts steps for migration procedure.

the only item we should do with usbmuxd is to `mask` the service to avoid it's startup and execution.
`mask` is a stronger version of `disable`. Using disable all symlinks of the specified unit file are removed. If using mask the units will be linked to /dev/null. This will be displayed if you check e.g. by systemctl status usbmuxd. The advantage of mask is to prevent any kind of activation, even manual:
```
systemctl mask usbmuxd
systemctl status usbmuxd
->
● usbmuxd.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
```

**Comment by vdelendik** [comment]
done, setup mcloud-agent using develop branch and test according to the https://github.com/zebrunner/stf/issues/535 steps

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-agent/tree/develop#mask-usbmuxd-service
use above steps to configure usbmuxd correctly on master host

**Comment by dhreben** [comment]
Verified.
