### ISSUE TITLE
add iOS 16.0 support

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#143]
subj

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-agent/commit/e4e7e4589612347752362f89f2b7418be3211ca2
also publish 16.0 dmg to the public s3 bucket: https://zebrunner-ce.s3.amazonaws.com/mcloud/DeveloperDiskImages/16.0/

**Comment by dhreben** [comment]
Verified on demo.zebrunner.farm:
Iphone 8 16.0 v.
Iphone 13 mini 16.1 v.

Opened separate ticket  https://github.com/zebrunner/mcloud-agent/issues/147
