### ISSUE TITLE
Error: binary operator expected after  run ./zebrunnner.sh start/stop

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#146]
Steps:

1../zebrunner.sh start 
2../zebrunner.sh stop

Actual result: /usr/local/bin/zebrunner-farm: line 199: [: /dev/device-LG: binary operator expected

<img width="584" alt="Screenshot 2022-10-19 at 16 32 27" src="https://user-images.githubusercontent.com/50950954/196705729-f48dfd36-9352-40e8-b615-33ef96efadcd.png">

**Comment by vdelendik** [comment]
hopefully I was able to fix but didn't test yet so setup/start/stop should be tested from scratch

**Comment by dhreben** [comment]
Still repro:

 **./zebrunner.sh stop** 

`/usr/local/bin/zebrunner-farm: line 197: [: /dev/device-LG: binary operator expected`

**./zebrunner.sh start**

`/usr/local/bin/zebrunner-farm: line 315: [: /dev/device-LG: binary operator expected`

**Comment by vdelendik** [comment]
stop/start, down/start -> everything is ok now. I suppose you didn't run ansible to redeploy new zebrunner-farm before verification. After fixing issue with comma several minutes ago I see everything works well

**Comment by dhreben** [comment]
yes, The issue was fixed after run ansible and redeploy new zebrunner-farm.
Closed
