### ISSUE TITLE
Don't show Ios device screen mirror

### ISSUE THREAD

**Issue by namilkimfree** [zebrunner/mcloud-agent#150]
how can i show the phone screen here? 

Ios os: 15
Phone: iphone 13
Xproj: 4.9.4

![20221123_213733](https://user-images.githubusercontent.com/44854923/203590296-d8dc3b8e-5c46-4e39-9ad1-7e1863c376b6.jpg)

If i restart ios device log -

Waiting until wda setting apprear 180 sec.

ERROR! Unable to get WDA settings from STF!

Appium log

sessionId:
[23/11/2022 04:45:44] Activating springboard app forcibly
[23/11/2022 04:50:07] Stopping 1st default WebDriverAgent session
Can you help me?

**Comment by vdelendik** [comment]
@namilkimfree, to insect the reason you have to analyze `/opt/zebrunner/wda-<udid>.log` file inside appium container.
```
docker exec -ti device-iPhone-....-appium bash
cat /opt/zebrunner/wda-udid.log
```

it might be related to https://github.com/zebrunner/appium/issues/147 which is going to be fixed in upcoming release
