### ISSUE TITLE
don't provide STF_PROVIDER_APPIUM_PORT anymore

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#154]
remove STF_PROVIDER_APPIUM_PORT env var declaration in zebrunner-farm script.
details:
https://github.com/zebrunner/stf/issues/234
https://github.com/zebrunner/mcloud-device/issues/115

**Comment by vdelendik** [comment]
done. to test we have to run iOS scripts somehow (maybe specific WebDriverAgent.ipa might be used).

**Comment by dhreben** [comment]
Verified
