### ISSUE TITLE
don't share WDA_ENV and log files in between containers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#155]
related tickets:
https://github.com/zebrunner/appium/issues/148
https://github.com/zebrunner/mcloud-device/issues/118

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-agent/pull/156
to test just setup single host and distributed setup using CE from develop branch
iOS devices should be available for both manual and automated usage

**Comment by dhreben** [comment]
Will be verified after fixed https://github.com/zebrunner/community-edition/issues/532

**Comment by dhreben** [comment]
Verified with CE+ec2.
Tested manually and automated behaviour.
