### ISSUE TITLE
for offline unhealthy android device do reconnect

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#162]
we disabled exit from container inside the healthcheck to avoid all kind of issues for scalable redroid simulators.
at the same time on real devices we can't recover device automatically when `adb devices` return offline device.

let's automate this particular use-case and do `adb reconnect` automatically as part of healthcheck...

**Comment by vdelendik** [comment]
done, @dhreben please re-setup mcloud-agent on stage using develop branch from this repo.
if no way to repro offline state you can do just these steps:
```
docker exec -ti <appium> bash
echo $EXIT_ON_ADB_FAILURE
```
-> this value should be equal to 1

**Comment by dhreben** [comment]
Verified.
