### ISSUE TITLE
Appium error:  An unknown server-side error occurred while processing the command. Could not proxy command to the remote server.

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#169]
logs:

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up[[[--udid 91JX1W8FW --name Pixel_3 --sessionId 4b6b782d-536d-4863-b522-99bc34331347]]]`

WorkAround: Restart device solve this issue

**Comment by vdelendik** [comment]
let's see how it's going with appium:2.0

**Comment by vdelendik** [comment]
it is fixed indirectly as for mobile native so for mobile web

**Comment by dhreben** [comment]
Fixed
