### ISSUE TITLE
Error: Unknown option detected after run zebrunner-farm

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#170]
**Steps:**

1.Enter zebrunner-farm

**Actual result:** Error: Unknown option detected after run zebrunner-farm

**Comment by vdelendik** [comment]
fixed. Unknown option will be disaplyed if invalid cli arg is provided, for example `zebrunner-farm start2`.
if non cli agr provided -> just help message should be displayed.

**Comment by dhreben** [comment]
Fixed
