### ISSUE TITLE
remove device volume with temp information on restart

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#180]
we added per each device `device-${device_name}-${udid}` docker volume to share temp `/tmp/log` content.
it contains all kind of logs and tracked artifacts (video recording etc).

there is no sense to keep it in between restart so on device down I'd recommend to remove this volume completely

**Comment by vdelendik** [comment]
fixed. to test do `zebrunner-farm down` and verify that such volumes deleted on stage:
```
local     device-HTC_10-F..9
local     device-HTC_U_Ultra-F..2
...
```

**Comment by dhreben** [comment]
Verified.
docker volume ls
zebrunner-farm down -> device volume is not present
