### ISSUE TITLE
remove WDA_IPA_PATH property as we decided to install WDA on iOS in advance and manually

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#182]
details might be found here: https://github.com/zebrunner/appium/issues/170

**Comment by vdelendik** [comment]
there is no sense to keep WDA_IPA_PATH as it is not used anymore in zebrunner-farm template. so let's remove it completely from `roles/devices/vars/main.yml.original`

**Comment by vdelendik** [comment]
done.

**Comment by dhreben** [comment]
Verified.
