### ISSUE TITLE
mask/disable usbmuxd automatically

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#186]
let's investigate an option to disable usbmuxd by ansible script.
till 2.4.7 it was a manual step in deployment.

The only question howto make it smarter and don't produce ansible error if it is already stopped and masked (disabled). Just disable code can be found below:
```
+#- name: Mask usbmuxd service
+#  command: systemctl stop usbmuxd && systemctl mask usbmuxd && systemctl status usbmuxd
```

**Comment by vdelendik** [comment]
done. we have to test 2 scenarios:
1. run ansible script when usbmuxd is stopped and disabled (done on my end already)
2. before running ansible explicitly unmask and start usbmuxd on Linux
-> after ansible script finish, usbmuxd is not running and service is masked/disabled

**Comment by dhreben** [comment]
Steps:
1. Run ansible
2. sudo service usbmuxd status

```
sudo: unable to resolve host mcloud
● usbmuxd.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
```
