### ISSUE TITLE
Add MacOS suport

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#191]
To deprecate mcloud-ios we have to certify current repo for the Mac. It should support for sure connected apple devices

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-agent/pull/194

@dhreben, please setup from scratch using master branch using mac-devices ansible roles:
```
ansible-playbook -vvv -i hosts mac-devices.yml
```

also it has sense to setup CE as well using master branch and 2.5 release... and do sanity check

**Comment by dhreben** [comment]
Verified.
