### ISSUE TITLE
make socat tcp listening proxy service for usbmuxd

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#192]
during ansible script we have to deploy LaunchAgent socat scipt to start tcp listening by usbmuxd:
```
socat TCP-LISTEN:2222,reuseaddr,fork UNIX-CONNECT:/var/run/usbmuxd
```

make sure to parametrize TCP-PORT using declaration in main.yml

**Comment by vdelendik** [comment]
so far hardcoded 2222 port. if no complains we can proceed as is.

**Comment by dhreben** [comment]
`UNIX-LISTEN:/var/run/usbmuxd,fork,reuseaddr,mode=777 TCP:appium:22 `- linux
`/usr/local/bin/socat TCP-LISTEN:2222,reuseaddr,fork UNIX-CONNECT:/var/run/usbmuxd` - mac os
