### ISSUE TITLE
add for status call `uptime` information

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#205]
let's improve status method and return information about uptime of the device containers.
it might be uptime for every component or the youngest among all 3 per device (appium, stf and uploader)

**Comment by vdelendik** [comment]
for `./zebrunner.sh status`command

**Comment by azarouski** [comment]
also we can add current restarts count
https://docs.docker.com/reference/cli/docker/container/run/#inspect-container-restarts
