### ISSUE TITLE
/host_mnt/private/var/db/lockdown: operation not permitted

### ISSUE THREAD

**Issue by sgusakovsky** [zebrunner/mcloud-agent#206]
Hello, I tried to add new iOs device, but faced unusual issue. Looks like private/var/db/lockdown folder are locked and can't be unlocked even if I use root. I use Mac OS Ventura. Could someone help me with it?

device-iPhone_14_Pro-00008120-001919562EEB401E-appium
device-iPhone_14_Pro-00008120-001919562EEB401E
device-iPhone_14_Pro-00008120-001919562EEB401E-uploader
device-iPhone_14_Pro-00008120-001919562EEB401E
iPhone_14_Pro creating...
3aa2c6ca5516adf60f1d52ecbc1d0aa801e5eb7cda574d65625705a69198ab90
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/var/db/lockdown': mkdir /host_mnt/private/var/db/lockdown: operation not permitted.
9c86d1a718bb19bdebf46f67d65f4ae3885d6f8cbed9446b9d25965ddff2b65d
08393a9cabd0851ee0fe278df6ab6550867ca7aae2fd866e208dcd7bf16063b1

device-iPhone_14_Pro-00008120-001919562EEB401E starting...
device-iPhone_14_Pro-00008120-001919562EEB401E
Error response from daemon: error while creating mount source path '/host_mnt/private/var/db/lockdown': mkdir /host_mnt/private/var/db/lockdown: operation not permitted
Error: failed to start containers: device-iPhone_14_Pro-00008120-001919562EEB401E-appium
device-iPhone_14_Pro-00008120-001919562EEB401E-uploader

**Comment by sgusakovsky** [comment]
Hi @vdelendik What additional info can I provide with you?

**Comment by vdelendik** [comment]
@sgusakovsky, could you please join https://t.me/zebrunner and ask about assistant.
That's pretty strange to see such path as for the container we are trying to share `/private/var/db/lockdown`
https://github.com/zebrunner/mcloud-agent/blob/09d67b136ddde93b83f4c797e06bee17b82c558f/roles/mac-devices/templates/zebrunner-farm#L156

using telegram channel we can organize a call and inspect your env

**Comment by vdelendik** [comment]
it should be fixed in v2.5.2. eta for official release is Aug, 29
@sgusakovsky ^^^

**Comment by dhreben** [comment]
Fixed
Verified after cloned from master branch
