### ISSUE TITLE
add info into the README about installing go ios on Mac OS

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#214]
Download v1.0.115+ go ios utility [go-ios-mac.zip](https://github.com/danielpaulus/go-ios/releases/download/v1.0.115/go-ios-mac.zip) and put into /usr/local/bin

Make sure to unblock it as it goes from not identified developer:
1. Open System settings
2. Privacy and Security
3. Apply access go ios

**Comment by vdelendik** [comment]
@dhreben do you remember why we need go ios on the mac itslef?

**Comment by vdelendik** [comment]
added into the master readme

**Comment by dhreben** [comment]
@vdelendik  As i know go-ios need to connect/control iOS devices on mac

Verified.
