### ISSUE TITLE
remove useless `mcloud-storage-volume:/opt/zebrunner` share

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#218]
https://github.com/zebrunner/mcloud-agent/blob/754f36eff719be8041749cedbc34254e41863a3b/roles/devices/templates/zebrunner-farm#L86

it seems like in v2.5 we removed all code which used `/opt/zebrunner`. Let's inspect again and remove volume share.
P.S. During upgrade it has sense to remove these volumes from the server

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-agent/pull/271
basic acceptance is ok

**Comment by dhreben** [comment]
Verified
