### ISSUE TITLE
remove useless `APPIUM_HOST` env var for appium container

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#219]
https://github.com/zebrunner/mcloud-agent/blob/754f36eff719be8041749cedbc34254e41863a3b/roles/devices/templates/zebrunner-farm#L97

**Comment by vdelendik** [comment]
done. basic acceptance executing android and ios jobs should be enough to close

**Comment by dhreben** [comment]
Basic acceptance  with iOS-Preferences-Test ,Mobile-iOS-Safari-Test ,  Android-Demo-Test  successfully completed. Video, screenshots and logs are available.
