### ISSUE TITLE
Devices are not available on STF  after reboot linux

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#220]
Steps:

1. sudo reboot now

Actual result: Devices are not available on STF  after reboot linux

log:
```
Unknown arguments: connectDevDealer, connectAppDealer
Exit status: 1
```

**Comment by vdelendik** [comment]
fixed via https://github.com/zebrunner/mcloud-device/issues/147

**Comment by dhreben** [comment]
Fixed
