### ISSUE TITLE
remove workaround for the dashes in `roles/devices/templates/mcloud-devices.txt`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#233]
no need to store both variants anymore

**Comment by vdelendik** [comment]
closing as invalid because no more workarounds for dashes removal in https://github.com/zebrunner/mcloud-agent/blob/ebe0df9f569b6b08d31337c128296eb1a52a2a2e/roles/devices/templates/mcloud-devices.txt#L2
only single declaration in the 3rd column for udid. the same for mac-devices roles!

**Comment by dhreben** [comment]
Сlosed
