### ISSUE TITLE
add info into the README switch off lock screen when inactive on Mac OS and Apple TV

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#240]
**Mac OS:**

Steps:
Settings->Lock screen->Turn display off when inactive->select Never

**Apple TV:**

Settings->General->Sleep after->Select never

**Comment by vdelendik** [comment]
done and merged to master

**Comment by dhreben** [comment]
Verified. The Apple TV description was displayed a bit incorrectly
<img width="611" alt="Screenshot 2023-09-07 at 16 00 35" src="https://github.com/zebrunner/mcloud-agent/assets/50950954/9e878dcf-cf44-4e98-b9a3-32c41707b3fe">


Added @akamarouski  empty line before lines
https://github.com/zebrunner/mcloud-agent/commit/ed79d30fd4c26b1b1486e42883b32c05a823b1ac
