### ISSUE TITLE
limit log size and organize rotation for containers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#245]
```
--log-driver local --log-opt max-size=10m
```
https://github.com/docker/for-mac/issues/5145
https://github.com/moby/moby/issues/41820

**Comment by vdelendik** [comment]
closing as won't fix. local log-fdirver and rotation didn't help. Upgraded docker to `Docker version 24.0.5, build ced0996`.
hopefully it might solve the problem

**Comment by vdelendik** [comment]
reopening as default HDD limit available for docker containers. We see 64Gb by default
![image](https://github.com/zebrunner/mcloud-agent/assets/4551455/45ba29e5-158c-4da2-9aa4-601f5e503eec)


so let's apply log rotation policy and specify 1Gb as a cap

**Comment by vdelendik** [comment]
closing together with #249

**Comment by dhreben** [comment]
Closed as duplicate
