### ISSUE TITLE
cannot Run ansible-playbook script

### ISSUE THREAD

**Issue by mazis0** [zebrunner/mcloud-agent#252]
hello, im get an error while execute ansible-playbook -vvv -i hosts mac-devices.yml on my macos(ventura), how to resolve the error? thanks 

ansible-playbook [core 2.15.4]
  config file = None
  configured module search path = ['/Users/muhammad.azis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/muhammad.azis/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.11/bin/ansible-playbook
  python version = 3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)] (/Library/Frameworks/Python.framework/Versions/3.11/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /Users/muhammad.azis/Documents/data/test100/mcloud-agent/hosts as it did not pass its verify_file() method
script declined parsing /Users/muhammad.azis/Documents/data/test100/mcloud-agent/hosts as it did not pass its verify_file() method
auto declined parsing /Users/muhammad.azis/Documents/data/test100/mcloud-agent/hosts as it did not pass its verify_file() method
Parsed /Users/muhammad.azis/Documents/data/test100/mcloud-agent/hosts inventory source with ini plugin
Read vars_file 'defaults/main.yml'
Read vars_file 'defaults/main.yml'
Read vars_file 'defaults/main.yml'
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks 
instead. See https://docs.ansible.com/ansible-
core/2.15/user_guide/playbooks_reuse_includes.html for details. This feature 
will be removed in version 2.16. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
statically imported: /Users/muhammad.azis/Documents/data/test100/mcloud-agent/roles/mac-devices/tasks/usbmuxd.yml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: mac-devices.yml ******************************************************
1 plays in mac-devices.yml
Read vars_file 'defaults/main.yml'
Read vars_file 'defaults/main.yml'
Read vars_file 'defaults/main.yml'

PLAY [devices_servers] *********************************************************
Read vars_file 'defaults/main.yml'

TASK [Gathering Facts] *********************************************************
task path: /Users/muhammad.azis/Documents/data/test100/mcloud-agent/mac-devices.yml:3
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: muhammad.azis
<localhost> EXEC /bin/sh -c 'echo ~muhammad.azis && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/muhammad.azis/.ansible/tmp `"&& mkdir "` echo /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223 `" && echo ansible-tmp-1695009284.271959-2189-111635118332223="` echo /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible/modules/setup.py
<localhost> PUT /Users/muhammad.azis/.ansible/tmp/ansible-local-21869lxof7me/tmpzh9dy_oe TO /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223/ /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-drfccykrqrnngnvdifkuyrxknaexgfre ; /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223/AnsiballZ_setup.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/muhammad.azis/.ansible/tmp/ansible-tmp-1695009284.271959-2189-111635118332223/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "ansible.legacy.setup": {
            "ansible_facts": {
                "discovered_interpreter_python": "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11"
            },
            "failed": true,
            "module_stderr": "sudo: a password is required\n",
            "module_stdout": "",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1,
            "warnings": [
                "Platform darwin on host localhost is using the discovered Python interpreter at /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.15/reference_appendices/interpreter_discovery.html for more information."
            ]
        }
    },
    "msg": "The following modules failed to execute: ansible.legacy.setup\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by vdelendik** [comment]
Hi @mazis0, take a look howto to provide sudo credentials in the readme: https://github.com/zebrunner/mcloud-agent#mac-os
```
ansible-playbook -vvv -i hosts --user=USERNAME --extra-vars "ansible_sudo_pass=PSWD" mac-devices.yml
```

also you can switch to root and do quit to have several minutes sudo permissions on the mac:
```
sudo su
exit
ansible-playbook -vvv -i hosts mac-devices.yml
```
2nd variant is more secure as you don't store password in the command history
