### ISSUE TITLE
bump up to latest appium:2.0.7

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#261]
subj

**Comment by vdelendik** [comment]
2.0.7-beta6 is inside develop. waiting for the official release build

**Comment by vdelendik** [comment]
done

**Comment by dhreben** [comment]
Basic acceptance  with iOS-Preferences-Test ,Mobile-iOS-Safari-Test ,  Android-Demo-Test  successfully completed. Video, screenshots and logs are available.
