### ISSUE TITLE
Wrap ansible command in OS detection script

### ISSUE THREAD

**Issue by azarouski** [zebrunner/mcloud-agent#274]
Let's add a script that will automatically detect server OS and select appropriate yaml file for ansible.

**Comment by azarouski** [comment]
To check this issue you need to try to [run ansible](https://github.com/zebrunner/mcloud-agent#run-ansible-playbook) on inappropriate systems e.g. 

on linux server run:
```bash
ansible-playbook -vvv -i hosts mac-devices.yml
```
on mac server run:
```bsah
ansible-playbook -vvv -i hosts devices.yml
```
---

The ansible script is supposed to exit with an error and not make any changes to the system.
`OS version is not compatible!`

**Comment by dhreben** [comment]
Verified.

**Linux:**

`ansible-playbook -vvv -i hosts mac-devices.yml`

```
fatal: [localhost]: FAILED! => {
    "assertion": "os.stdout is search(\"Darwin\")",
    "changed": false,
    "evaluated_to": false,
    "msg": "OS version is not compatible!"
```

**Mac:** 

`ansible-playbook -vvv -i hosts devices.yml`

```
fatal: [localhost]: FAILED! => {
    "assertion": "os.stdout is search(\"Linux\")",
    "changed": false,
    "evaluated_to": false,
    "msg": "OS version is not compatible!"
```
