### ISSUE TITLE
can't control ios devices

### ISSUE THREAD

**Issue by tuyenlq** [zebrunner/mcloud-agent#278]
Hi,

I installed mcloud on ubuntu and mcloud-agent on macos.

Installed and connected successfully but i but I can't control the device

![image](https://github.com/zebrunner/mcloud-agent/assets/10045154/5018d2b5-e440-48d8-977d-a257bf8266cc)

![image](https://github.com/zebrunner/mcloud-agent/assets/10045154/1f8c38cc-07d0-4b10-8411-bf0b7aac7c7d)
![image](https://github.com/zebrunner/mcloud-agent/assets/10045154/a95737ec-1ab1-4827-9dba-9a95d5261ea0)

**Server**

Ubuntu :  Ubuntu 20.04.6 LTS
IP : 10.x.x.36

**Provider**

Macos  :  macos Big Sur - 11.7.10
IP : 10.x.x.142
Iphone 7  - version 13.1

Config on mac devices - file main.yml
[main.txt](https://github.com/zebrunner/mcloud-agent/files/13495824/main.txt)

=====
logs on docker
[logs_docker.txt](https://github.com/zebrunner/mcloud-agent/files/13495884/logs_docker.txt)
[agents.log](https://github.com/zebrunner/mcloud-agent/files/13495912/agents.log)

Thanks for support

**Comment by vdelendik** [comment]
@tuyenlq, 1st of all check if network connection is allowed.

1. open device and test that on the agent host we have listening on 7434 port
`netstat -an | grep 7434`
2. test connectivity from .36 to .142
`telnet 10.x.x.142 7434`
-> telnet should established connection. I suppose in your case it couldn't establish it. Ask IT howto open ports in between servers.

**Comment by mit4ever** [comment]
re-open
