### ISSUE TITLE
Got "Syntax Error while loading YAML." on  /roles/devices/vars/main.yml

### ISSUE THREAD

**Issue by MHabiib** [zebrunner/mcloud-agent#294]
<img width="901" alt="image" src="https://github.com/zebrunner/mcloud-agent/assets/42311916/cb1d046a-78f8-45c9-a10b-e31e48b0d4be">

**Comment by MHabiib** [comment]
to solve this issue add whitespace on /roles/devices/vars/main.yml file
<img width="693" alt="image" src="https://github.com/zebrunner/mcloud-agent/assets/42311916/23440bbd-23dd-43c7-9c93-3073303b47ee">

**Comment by vdelendik** [comment]
fixed, changes are in the develop branch
