### ISSUE TITLE
move adb and usbmuxd into the dedicated alpine docker images

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#302]
to support mcloud setup without automation we have to investigate possibility to use adb/usbmuxd/rsd tunnel in micro alpine images.
and start appium when automation is needed

**Comment by azarouski** [comment]
- For `adb` we already have https://github.com/zebrunner/mcloud-android-connector
- For `usbmuxd` we already have https://github.com/zebrunner/mcloud-ios-connector

**Comment by dhreben** [comment]
Verified.
