### ISSUE TITLE
move appium uiautomator2 uninstall to the ansible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#310]
we don't do uninstall everytime on appium container restart due to the google appstore security permissions:
https://github.com/zebrunner/appium/issues/365

but at the same time during upgrade from one appium to another it might be a must to reinstall.
so let's move these steps onto the ansible script if possible. if not, organize complex logic in between to be able to uninstall 1st time after upgrade

**Comment by azarouski** [comment]
it seems like ift fixed by appium already:
https://github.com/appium/appium-uiautomator2-driver/blob/afaab2f1610f94f03a4328f57bc2b52d710dac95/lib/uiautomator2.js#L141
older version of uiautomator2 should be reinstalled automatically^^^
