### ISSUE TITLE
WdaMjpeg connection was closed  iOS 17.4-17.5

### ISSUE THREAD

**Issue by yaroslav796** [zebrunner/mcloud-agent#317]
Hello! 
I'm having trouble connecting to iOS 17.4-17.5. (Versions below 17 work fine.)
In STF, the device status is "pending". In the container logs, I noticed the message "WdaMjpeg connection was closed". 
This could be the issue. 
Locally, using appium 2.5.4 + appium inspector, I can connect to the device and there's an image. 
When adding the parameter "appium:mjpegServerPort": 8101 or any other port, there's no image.

Host + Provider mac mini intel (sonoma)
[STF provider container.txt](https://github.com/zebrunner/mcloud-agent/files/15325770/STF.provider.container.txt)
[appium and WebDriverAgent for iOS container.txt](https://github.com/zebrunner/mcloud-agent/files/15325775/appium.and.WebDriverAgent.for.iOS.container.txt)

**Comment by vdelendik** [comment]
@yaroslav796, from time to time we see something similar on SE devices when mjpeg streaming is blocked.
I'd recommend to reboot device and reinstall WDA on it. Feel free to reopen ticket if still repro. And in this case, please attach also from appium container such log file: `/tmp/log/wda.log`
