### ISSUE TITLE
integrate stf url and token vars to move devices into Unheathly state

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#318]
https://github.com/zebrunner/appium/pull/386

**Comment by vdelendik** [comment]
done. templates for variables added into defaults/main.yml. Also zebrunner-farm shell script updated accordingly for linux and mac.
@dhreben, to test we have to reproduce any major issue like this one: https://github.com/zebrunner/appium/pull/386/files#diff-d7839b928c1c681dd6c213ca3ad4daf129cd12d82f059cd02e87a13cfeea94dfR459

After that appium should move device into the Unhealthy state and device will be excluded from the automation usage until manual review and restore.

**Comment by vdelendik** [comment]
let's move these settings from default/main.yml to roles main.yml

**Comment by vdelendik** [comment]
moved, settings applied on stage linux. testing scenario can be founf in previous comment: 
https://github.com/zebrunner/mcloud-agent/issues/318#issuecomment-2117893501

**Comment by dhreben** [comment]
Verified
