### ISSUE TITLE
WdaClient Not working after running automation in ios devices through linux

### ISSUE THREAD

**Issue by ayushanurag2002** [zebrunner/mcloud-agent#330]
After running automation in ios devices using appium through linux provider the ios device is not taking any touch after that. After automation the ios device is not taking any touch but the home button is working fine . Even if there are any manual touch during automation the device stops responding after that.
![ios](https://github.com/zebrunner/mcloud-agent/assets/92075240/93a2abdf-4b84-4b0b-b8de-7e2b4f6e79d5)

**Comment by vdelendik** [comment]
@ayushanurag2002, what's inside connector container logs? also, provide exact steps as I see it might be mix of automation and manual usage so we can reproduce on our end...

**Comment by ayushanurag2002** [comment]
thanks for you response but we were able to solve the issue by error handling in some parts of the wdaclient.js file
