### ISSUE TITLE
automate or provide instructions howto mount `Developer Image` for iOS devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#47]
{"err":"Could not start service:com.apple.instruments.remoteserver.DVTSecureSocketProxy with reason:'InvalidService'. Have you mounted the Developer Image?","level":"fatal","msg":"processcontrol failed","time":"2021-12-09T09:25:08Z"}

https://github.com/zebrunner/stf/pull/263/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22
and
https://github.com/zebrunner/stf/pull/263/files#diff-e20bab65472b09a5c0acf0c33982552c9f46745b1fdd23a65c76ec33cefb8c3eR23

we have to declare a volume as part of mcloud-agent and push into aws s3 default content... think about re-downloading or symlinking missed images on the fly

**Comment by vdelendik** [comment]
automated via ansible script.
to test it is recommended to
1. shutdown mcloud-agent on STAG env
-> verify that `appium-storage-volume` and `mcloud-storage-volume` removed
2. setup mcloud-agent
->  `mcloud-storage-volume` should appear
3. start devices and verify that mcloud-storage-volume is used by appium container
-> bash into any iOS/Android appium container and do `ls -la /opt/zebrunner/DeveloperDiskImages/`. It should have images folder from 12.0 to 15.2!

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-01-13 at 20 22 29](https://user-images.githubusercontent.com/50950954/149378360-8c41ad7f-5652-4977-92a7-18173b2d9fd6.png)
