### ISSUE TITLE
STF is active on iOS devices if service usbmuxd  stopped

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#65]
**Steps:**

1. Sudo service usbmuxd stop
2. Open STF

**Actual result**: STF is active on iOS devices if service usbmuxd is stopped

**Expected result:**  STF should be inactive on iOS devices if service usbmuxd is stopped

**Comment by vdelendik** [comment]
moved to 2.1 as priority is low now after fixing #60

**Comment by vdelendik** [comment]
1. It make sense to verify usbmuxd service status before exit and return 0 if service stopped
-> it should guarantee we don’t restart services forever

2. as about usbmuxd process kill let’s double check that tgis service has always restart policy
https://serverfault.com/questions/918392/systemd-not-restarting-my-process

**Comment by vdelendik** [comment]
@dhreben, let's test if adding `ExecStopPost` to usbmuxd service `/lib/systemd/system/usbmuxd.service` might help
```
ExecStopPost=/usr/local/bin/zebrunner-farm down ios
```

after your confirmation we can just update readme
