### ISSUE TITLE
document required steps to enable iOS mobile and web testing

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#70]
we have to recommend to enable:
Settings -> Developer -> Enable UI Automation
and
Settings -> Safari -> Advanced -> Web Inspector

**Comment by vdelendik** [comment]
fixed, overall README.txt steps updated in develop branch: https://github.com/zebrunner/mcloud-agent/blob/develop/README.md

Please, verify english, logical steps etc

**Comment by okamara** [comment]
Verified on develop, fixed.
