### ISSUE TITLE
ansible preparation should forcibly re-download images

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#72]
we have to forcibly redownload appium, mcloud-device and maybe new image with developer images during ansible script execution.
As of now if new 1.22 appium is pushed ansible still can't detect it. Also think about numbering it on our own starting from 1.0 in appium!!! That's should allow to reuse all the benefits of patch numbers

**Comment by vdelendik** [comment]
also add explicit appium image pull from aws ecr registry

**Comment by vdelendik** [comment]
fixed. appium docker image should be downloaded as part of ansible script now.
to test I can recommend to 
1. shutdown mcloud-agent
2. remove manually all `public.ecr.aws/zebrunner/appium` docker images from the server.
3. run ansible script
-> verify that appium image is downloaded

**Comment by dhreben** [comment]
**Steps:**

1../zebrunner.sh shutdown
2. remove manually all public.ecr.aws/zebrunner/appium docker images from the server.
3.Run ansble script

**Actual result :**  msg": "AnsibleUndefinedVariable: 'STF_DOCKER_NETWORK' is undefined"
```


<localhost> EXEC /bin/sh -c 'rm -f -r /home/build/.ansible/tmp/ansible-tmp-1642091118.65-17551-161745603314249/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'STF_DOCKER_NETWORK' is undefined"
}
```

**Comment by vdelendik** [comment]
@dhreben, you forgot to do `./zebrunner.sh setup` after shutdown:)

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-01-13 at 20 07 10](https://user-images.githubusercontent.com/50950954/149376086-335a9a14-5c31-46c9-ba31-ad90b1ac9c69.png)
