### ISSUE TITLE
`start/stop/restart/status` operations should be done vs whiteliested and connected devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#75]
our regular `./zebrunner.sh start` operation do actual start for every connected device. 
it would be greate to perform vs connected and whitelisted otherwise we can't read valid device properties aka udid, platform name etc and bash operation can't generate containers correctly!

**Comment by vdelendik** [comment]
done.

**Comment by dhreben** [comment]
Verified.
