### ISSUE TITLE
rename devices.txt to mcloud-devices.txt as template 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#76]
let's rename devices.txt template file to mcloud-devices.txt to be able to keep on the same server both versions: 1.x and 2.x.

**Comment by vdelendik** [comment]
done. to test just pull latest changes from develop branch and run ansible script.
-> all whitelisted devices should work as expected /usr/loca/bin/mcloud-devices.txt is generated.
also make sure to restart something and do shutdown which much remove this file at the end

**Comment by dhreben** [comment]
Veriifed.
![Screenshot 2022-01-13 at 20 48 14](https://user-images.githubusercontent.com/50950954/149382378-fbef2fe2-4b20-4193-81ea-47e197bf84b0.png)
