### ISSUE TITLE
too inconvenient way to manage and share developer images 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#81]
we have to find better way for downloading and sharing developer images... It seems like extracting locally to the server and sharing into the appium container is much easier because we can partially add missed patch versions or similar...

**Comment by vdelendik** [comment]
done. all dmg files are published independently to public aws s3 bucket so we can download and update partially.
also instead of get_url reuse `wget -N` which detect that file already downloaded and has the same content in 10-20 times faster.
And finally loaded binary content pushed onto the `mcloud-storage-volume` docker volume as in previous implementation.

For testing better to setup mcloud on clean instance or do shutdown for macloud-agent and setp again
-> iOS devices should be mounted successfully after reconnect or reboot after setup

**Comment by dhreben** [comment]
Verified.
