### ISSUE TITLE
Mcloud.p12 file is not replaced after adding new one

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#89]
**Steps:**

 1. copy new mcloud.p12 file in home/build/tools

2. cd opt/zebrunner/mcloud.p12

**Actual result:** Mcloud.p12 file is not replaced after adding new one

**Comment by vdelendik** [comment]
fixed. mcloud.p12 is not shared anymore to avoid all kind of negative impact. added mcloud.p12 copying as part of registerDevices ansible script.

**Comment by dhreben** [comment]
Verified.
