### ISSUE TITLE
udev removals haven't serial id/udid for some devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-agent#92]
let's investigate what migh tbe improved in udev rules to detect id serial shot in 100% for both Android and iOS.
Related topics:
https://stackoverflow.com/questions/66482363/linux-udev-rule-on-removal-need-more-information-to-take-action
https://unix.stackexchange.com/questions/368122/problems-with-udev-rules-for-starting-bash-script-when-hdd-is-disconnected

**Comment by vdelendik** [comment]
done. during the testing we have verify single and mass connect/removal for devices connected directly or via hub.

**Comment by dhreben** [comment]
Verified.
