### ISSUE TITLE
It makes sense to do a restart on the iOS and Android platforms

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#99]
for example: 

```
zebrunner-farm restart ios
zebrunner-farm restart android
```

**Comment by vdelendik** [comment]
done. please, test:
start/stop/down/restart and status - all of them should be able to operate by platform name: `ios` or `android` - only in lower case!

**Comment by dhreben** [comment]
**Case 1: ./zebrunner.sh stop android  or  zebrunner-farm stop android**

1.` docker ps -a`

- Android containers have status **UP**

2.   `./zebrunner.sh stop android`

**Actual result :**  /usr/local/bin/zebrunner-farm: line 186

```
(base) build@mcloud:~/tools/mcloud-agent$ ./zebrunner.sh stop android
ACTION: stop
/usr/local/bin/zebrunner-farm: line 186: [: missing `]'

device-Samsung_Galaxy_S5-4d0.......1e7 stopping...
/usr/local/bin/zebrunner-farm: line 217: /tmp/device-Samsung_Galaxy_S5-4.........1e7.log: Permission denied
device-Samsung_Galaxy_S5-4d0.....d21e7
/usr/local/bin/zebrunner-farm: line 219: /tmp/device-Samsung_Galaxy_S5-4d0.....1e7-appium.log: Permission denied
device-Samsung_Galaxy_S5-4d003e....1e7-appium

```
**Case 2: ./zebrunner.sh start android or zebrunner-farm start android** 

1.` docker ps -a`

- Android containers have status **Exited**

2.   `./zebrunner.sh start android`

**Actual result** :  /usr/local/bin/zebrunner-farm: line 299

```
(base) build@mcloud:~/tools/mcloud-agent$ zebrunner-farm stop android
ACTION: stop
/usr/local/bin/zebrunner-farm: line 186: [: missing `]'

device-Samsung_Galaxy_S5-4d003....1e7 stopping...
/usr/local/bin/zebrunner-farm: line 217: /tmp/device-Samsung_Galaxy_S5-4d0....21e7.log: Permission denied
device-Samsung_Galaxy_S5-4d003e5f4aad21e7
/usr/local/bin/zebrunner-farm: line 219: /tmp/device-Samsung_Galaxy_S5-4d003.....21e7-appium.log: Permission denied
device-Samsung_Galaxy_S5-4d003e...7-appium

```
**Case 3../zebrunner.sh restart android  or  zebrunner-farm restart android**

1.` docker ps -a`

- Android containers have status **UP**

2.   `./zebrunner.sh restart android`

**Actual result :**  /usr/local/bin/zebrunner-farm: line 228

```
(base) build@mcloud:~/tools/mcloud-agent$ ./zebrunner.sh restart android
ACTION: down
/usr/local/bin/zebrunner-farm: line 228: [: missing `]'
/usr/local/bin/zebrunner-farm: line 260: /tmp/device-Samsung_Galaxy_S5-4d003......1e7.log: Permission denied
device-Samsung_Galaxy_S5-4d.....1e7
/usr/local/bin/zebrunner-farm: line 266: /tmp/device-Samsung_Galaxy_S5-4d0.....21e7-appium.log: Permission denied
device-Samsung_Galaxy_S5-4d......21e7-appium

```
**Case 4../zebrunner.sh down android  or  zebrunner-farm down android**

1.` docker ps -a`

- Android containers have status **UP**

2.   `./zebrunner.sh down android`

**Actual result :**  /usr/local/bin/zebrunner-farm: line 228

```
(base) build@mcloud:~/tools/mcloud-agent$ ./zebrunner.sh restart android
ACTION: down
/usr/local/bin/zebrunner-farm: line 228: [: missing `]'
/usr/local/bin/zebrunner-farm: line 260: /tmp/device-Samsung_Galaxy_S5-4d.....1e7.log: Permission denied
device-Samsung_Galaxy_S5-4d00......1e7
/usr/local/bin/zebrunner-farm: line 266: /tmp/device-Samsung_Galaxy_S5-4d......d21e7-appium.log: Permission denied
device-Samsung_Galaxy_S5-4d003.....d21e7-appium

```
**Case 5../zebrunner.sh status android  or  zebrunner-farm status android**

1. ./zebrunner.sh status android

**Actual result :**  /usr/local/bin/zebrunner-farm: line 340

```
(base) build@mcloud:~/tools/mcloud-agent$ ./zebrunner.sh status android
ACTION: status
/usr/local/bin/zebrunner-farm: line 340: [: missing `]'
device-Samsung_Galaxy_S10-R2.............YQY - DISCONNECTED

device-- - DISCONNECTED

device-- - DISCONNECTED

device-- - DISCONNECTED

device-Samsung_Galaxy_S5-4d003......d21e7
Appium: "healthy"; STF: "healthy"

device-Nokia_3-NE1GA.....5862
Appium: "healthy"; STF: "healthy"

device-- - DISCONNECTED

device-- - DISCONNECTED

device-Samsung_Galaxy_S6-03........6915
Appium: "healthy"; STF: "healthy"

device-- - DISCONNECTED

device-- - DISCONNECTED

device-- - DISCONNECTED

device-LG_G6-LG........8e7
Appium: "healthy"; STF: "healthy"
```

**Comment by vdelendik** [comment]
1. fixed mistake with missing ']' symbol
2. fixed status call ignoring empty devices
3. errors with permissions denied is not  bug. somebody generated such logs under the root and locked 
to fix remove all logs under the root: `sudo rm -f /tmp/*.log`

**Comment by dhreben** [comment]
**Case 1:**
 

- zebrunner-farm stop android          --->  Passed
- zebrunner-farm start android           ---> Passed
- zebrunner-farm stop ios                   ---> Passed
- zebrunner-farm start ios                 - -->  Passed

**Case 2:**

- ./zebrunner.sh stop android              ---> Passed
- ./zebrunner.sh start android             ---> Passed
- ./zebrunner.sh stop ios                      ---> Passed
- ./zebrunner.sh start ios                     ---> Passed


**Case 3:**
 

-  zebrunner-farm restart android         ---> Passed
-  zebrunner-farm restart ios                ---> Passed
- ./zebrunner.sh restart android            ---> Passed
- ./zebrunner.sh restart ios                    ---> Passed

**Case 4:**

- zebrunner-farm down android             ---> Passed
- zebrunner-farm down ios                     ---> Passed
- ./zebrunner.sh down android              ---> Passed
- ./zebrunner.sh down ios.                     ---> Passed


 **Case 5:**. 


- zebrunner-farm status android           ---> Passed
- zebrunner-farm status ios                   ---> Passed
- ./zebrunner.sh status android             ---> Passed
- ./zebrunner.sh status ios                    ---> Passed
